# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

version: 2

builds:
  - main: ./cmd/sheltie
    binary: sheltie
    ldflags:
      # Sets the version variable in the build package to the build version prefixed with a 'v'
      # Sets the main.date to a static date for checksum verification. See https://goreleaser.com/customization/builds/#reproducible-builds.
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser -X github.com/parkan/sheltie/pkg/build.version=v{{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 'amd64'
      - 'arm64'
    # Change to a static date for checksum verification. See https://goreleaser.com/customization/builds/#reproducible-builds.
    mod_timestamp: '{{.CommitTimestamp}}'
    env:
      - CGO_ENABLED=0
universal_binaries:
  - replace: true
archives:
  - format_overrides:
    - goos: windows
      format: zip
    - goos: darwin
      format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}mac_os
      {{- else }}{{ .Os }}{{ end }}_{{ .Arch }}
release:
  mode: keep-existing
  header: |
    ## changes from lassie

    - ripped out bitswap and graphsync. http only, no negotiation overhead
    - switched from legacy ipni to delegated routing v1 api for provider discovery
    - added frontier traversal: when a provider returns an incomplete car, we continue fetching missing blocks from other providers. efficiently handles the case where content is split across multiple nodes
    - full client-side implementation of the trustless gateway spec, including entity-bytes range requests
    - streaming extraction (--extract): writes files directly to disk as blocks arrive. no intermediate car, no seeking, no car extract required. handles chunked files, deduplication, and out-of-order block arrival
changelog:
  disable: true
